[package]
name = "rt-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["cargo", "derive"] }
rt-core = { version = "0.1.0", path = "../rt-core" }
rt-renderer = { version = "0.1.0", path = "../rt-renderer" }
rt-scene = { version = "0.1.0", path = "../rt-scene" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
toml = "1.1.4"
