[package]
name = "rt-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
fastrand = "2.4.1"
image = "0.25"
rayon = "1.10"
rt-core = { version = "0.1.0", path = "../rt-core" }
rt-scene = { version = "0.1.0", path = "../rt-scene" }

[dev-dependencies]
axum-test = "20.1.0"
criterion = "0.8.2"
insta = "1.47.2"
proptest = "1.11.0"
tokio-test = "0.4.5"
