@baseUrl = http://127.0.1.1:3000

# Scene
POST {{baseUrl}}/scene
Content-Type: application/json

{
  "background": {
      "type": "solid",
      "color": [0.0, 0.0, 0.0]
  },
  "materials": {
    "red": {
      "type": "lambertian",
      "albedo": [0.65, 0.05, 0.05]
    },
    "white": {
      "type": "lambertian",
      "albedo": [0.73, 0.73, 0.73]
    },
    "green": {
      "type": "lambertian",
      "albedo": [0.12, 0.45, 0.15]
    },
    "light": {
      "type": "diffuse_light",
      "emit": [15.0, 15.0, 15.0]
    }
  },
  "objects": [
    {
      "type": "quad",
      "q": [555.0, 0.0, 0.0],
      "u": [0.0, 555.0, 0.0],
      "v": [0.0, 0.0, 555.0],
      "material": "green"
    },
    {
      "type": "quad",
      "q": [0.0, 0.0, 0.0],
      "u": [0.0, 555.0, 0.0],
      "v": [0.0, 0.0, 555.0],
      "material": "red"
    },
    {
      "type": "quad",
      "q": [0.0, 0.0, 0.0],
      "u": [555.0, 0.0, 0.0],
      "v": [0.0, 0.0, 555.0],
      "material": "white"
    },
    {
      "type": "quad",
      "q": [555.0, 555.0, 555.0],
      "u": [-555.0, 0.0, 0.0],
      "v": [0.0, 0.0, -555.0],
      "material": "white"
    },
    {
      "type": "quad",
      "q": [0.0, 0.0, 555.0],
      "u": [555.0, 0.0, 0.0],
      "v": [0.0, 555.0, 0.0],
      "material": "white"
    },
    {
      "type": "quad",
      "q": [343.0, 554.0, 332.0],
      "u": [-130.0, 0.0, 0.0],
      "v": [0.0, 0.0, -105.0],
      "material": "light"
    }
  ]
}

###

# Camera
PUT {{baseUrl}}/camera
Content-Type: application/json

{
  "aspect_ratio": 1.7777778,
  "image_width": 1920,
  "fov": 38.5,
  "look_from": [ 278, 278, -800 ],
  "look_at": [ 278, 278, 0 ],
  "vup": [
    0,
    1,
    0
  ],
  "samples_per_pixel": 50,
  "defocus_angle": 0,
  "focus_dist": 1
}

###

# render
POST {{baseUrl}}/render
Content-Type: application/json

{
}
